version: '3.8'

services:
  frontend:
    build: ./material-applications/example-frontend
    image: example-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 5000:5000

  backend:
    build: ./material-applications/example-backend
    image: example-backend
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    ports:
      - 8080:8080

  redis:
    build: redis:latest
    image: redis

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
